# Site settings
title: My Blog
description: A Jekyll blog powered by GitHub Pages
author: riches31
email: riches31@gmail.com

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Just the Docs theme configuration
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "//github.com/riches31/blog"

# Footer content
footer_content: "Copyright &copy; 2025. Powered by Jekyll and Just the Docs."

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# GitHub Pages URL configuration
baseurl: "/blog" # Repository name in lowercase
url: "https://riches31.github.io" # GitHub Pages URL

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - LICENSE
  - CLAUDE.md
  - todo.md
